# Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

[main]
cm = org.apache.shiro.authc.credential.PasswordMatcher
iniRealm.credentialsMatcher = $cm

[users]
admin="$shiro2$argon2id$v=19$t=1,m=65536,p=4$8OmzyChZM9YkbtE+mOQ3jw$ySb95KDmhsC6GYDkxxGFEvDHNACudCj+pXNm5dFdfTE",ping
user1="$shiro2$argon2id$v=19$t=1,m=65536,p=4$ASE5RQRDOqXApXOiLW1V6A$Y0xeJW4vezZ7LSchwwPtXORp6RtfEw+AmoTwYy3Szxc"

[urls]
/$/ping = authcBasic,roles[ping]
/ds = authcBasic
/**=anon
