/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 *   SPDX-License-Identifier: Apache-2.0
 */
package org.apache.jena.sparql.lang.arq.javacc ;

// Not generated by javacc: the grammar uses option USER_CHAR_STREAM.
// Based on SimpleCharStream.java as generated by javacc 7.0.12, with:
//   "implements CharStream"
//   ExpandBuff doubles the buffer size, as in javacc PRs 303 and 317 (GH-1324)
//   Line and column are not stored for each char in the buffer.
//     They are kept for the start of the current token and
//     the end of the token is calculated when asked for.
//   getTrackLineColumn and setTrackLineColumn are public, as required by CharStream

/**
 * An implementation of interface CharStream, where the stream is assumed to
 * contain only ASCII characters (without unicode processing).
 */

public class SimpleCharStream implements CharStream
{
/** Whether parser is static. */
  public static final boolean staticFlag = false;
  int bufsize;
  int available;
  int tokenBegin;
/** Position in buffer. */
  public int bufpos = -1;

  // Line and column of the char at tokenBegin, and the CR/LF state after it.
  protected int column = 0;
  protected int line = 1;

  protected boolean prevCharIsCR = false;
  protected boolean prevCharIsLF = false;

  // False until the first char is read; line and column are then 0, as javacc's SimpleCharStream.
  private boolean tokenStarted = false;

  // Line and column of the char at endBufpos, calculated from those of the char at endTokenBegin.
  private char[] endBuffer = null;
  private int endTokenBegin;
  private int endBufpos;
  private int endLine;
  private int endColumn;
  private boolean endPrevCharIsCR;
  private boolean endPrevCharIsLF;

  protected java.io.Reader inputStream;

  protected char[] buffer;
  protected int maxNextCharInd = 0;
  protected int inBuf = 0;
  protected int tabSize = 1;
  protected boolean trackLineColumn = true;

  public void setTabSize(int i) { tabSize = i; }
  public int getTabSize() { return tabSize; }



  protected void ExpandBuff(boolean wrapAround)
  {
    int newBufsize = bufsize << 1;
    char[] newbuffer = new char[newBufsize];

    try
    {
      if (wrapAround)
      {
        System.arraycopy(buffer, tokenBegin, newbuffer, 0, bufsize - tokenBegin);
        System.arraycopy(buffer, 0, newbuffer, bufsize - tokenBegin, bufpos);
        buffer = newbuffer;

        maxNextCharInd = (bufpos += (bufsize - tokenBegin));
      }
      else
      {
        System.arraycopy(buffer, tokenBegin, newbuffer, 0, bufsize - tokenBegin);
        buffer = newbuffer;

        maxNextCharInd = (bufpos -= tokenBegin);
      }
    }
    catch (Throwable t)
    {
      throw new Error(t.getMessage());
    }


    bufsize = newBufsize;
    available = bufsize;
    tokenBegin = 0;
  }

  protected void FillBuff() throws java.io.IOException
  {
    if (maxNextCharInd == available)
    {
      if (available == bufsize)
      {
        if (tokenBegin > 2048)
        {
          bufpos = maxNextCharInd = 0;
          available = tokenBegin;
        }
        else if (tokenBegin < 0)
          bufpos = maxNextCharInd = 0;
        else
          ExpandBuff(false);
      }
      else if (available > tokenBegin)
        available = bufsize;
      else if ((tokenBegin - available) < 2048)
        ExpandBuff(true);
      else
        available = tokenBegin;
    }

    int i;
    try {
      if ((i = inputStream.read(buffer, maxNextCharInd, available - maxNextCharInd)) == -1)
      {
        inputStream.close();
        throw new java.io.IOException();
      }
      else
        maxNextCharInd += i;
      return;
    }
    catch(java.io.IOException e) {
      --bufpos;
      backup(0);
      if (tokenBegin == -1)
        tokenBegin = bufpos;
      throw e;
    }
  }

/** Start. */
  public char BeginToken() throws java.io.IOException
  {
    // Move line and column on from the start of the previous token to its last char.
    if (tokenStarted)
      lineColumnTo(bufpos);
    endBuffer = null;
    tokenBegin = -1;
    char c = readChar();
    tokenBegin = bufpos;
    UpdateLineColumn(c);
    tokenStarted = true;

    return c;
  }

  protected void UpdateLineColumn(char c)
  {
    column++;

    if (prevCharIsLF)
    {
      prevCharIsLF = false;
      line += (column = 1);
    }
    else if (prevCharIsCR)
    {
      prevCharIsCR = false;
      if (c == '\n')
      {
        prevCharIsLF = true;
      }
      else
        line += (column = 1);
    }

    switch (c)
    {
      case '\r' :
        prevCharIsCR = true;
        break;
      case '\n' :
        prevCharIsLF = true;
        break;
      case '\t' :
        column--;
        column += (tabSize - (column % tabSize));
        break;
      default :
        break;
    }
  }

  // Move line, column and the CR/LF state from the char at tokenBegin to the char at pos.
  private void lineColumnTo(int pos)
  {
    if (endBuffer == buffer && endTokenBegin == tokenBegin && endBufpos == pos)
    {
      line = endLine;
      column = endColumn;
      prevCharIsCR = endPrevCharIsCR;
      prevCharIsLF = endPrevCharIsLF;
      return;
    }
    int i = tokenBegin;
    for (int n = (pos - tokenBegin + bufsize) % bufsize; n > 0; n--)
    {
      if (++i == bufsize)
        i = 0;
      UpdateLineColumn(buffer[i]);
    }
  }

  // Calculate the line and column of the char at bufpos.
  private void calcEnd()
  {
    if (endBuffer == buffer && endTokenBegin == tokenBegin && endBufpos == bufpos)
      return;
    int beginLine = line;
    int beginColumn = column;
    boolean beginPrevCharIsCR = prevCharIsCR;
    boolean beginPrevCharIsLF = prevCharIsLF;
    lineColumnTo(bufpos);
    endLine = line;
    endColumn = column;
    endPrevCharIsCR = prevCharIsCR;
    endPrevCharIsLF = prevCharIsLF;
    endBuffer = buffer;
    endTokenBegin = tokenBegin;
    endBufpos = bufpos;
    line = beginLine;
    column = beginColumn;
    prevCharIsCR = beginPrevCharIsCR;
    prevCharIsLF = beginPrevCharIsLF;
  }

/** Read a character. */
  public char readChar() throws java.io.IOException
  {
    if (inBuf > 0)
    {
      --inBuf;

      if (++bufpos == bufsize)
        bufpos = 0;

      return buffer[bufpos];
    }

    if (++bufpos >= maxNextCharInd)
      FillBuff();

    return buffer[bufpos];
  }

  /**
   * @deprecated
   * @see #getEndColumn
   */
  @Deprecated
  public int getColumn() {
    return getEndColumn();
  }

  /**
   * @deprecated
   * @see #getEndLine
   */
  @Deprecated
  public int getLine() {
    return getEndLine();
  }

  /** Get token end column number. */
  public int getEndColumn() {
    if (!tokenStarted)
      return 0;
    calcEnd();
    return endColumn;
  }

  /** Get token end line number. */
  public int getEndLine() {
    if (!tokenStarted)
      return 0;
    calcEnd();
    return endLine;
  }

  /** Get token beginning column number. */
  public int getBeginColumn() {
    return tokenStarted ? column : 0;
  }

  /** Get token beginning line number. */
  public int getBeginLine() {
    return tokenStarted ? line : 0;
  }

/** Backup a number of characters. */
  public void backup(int amount) {

    inBuf += amount;
    if ((bufpos -= amount) < 0)
      bufpos += bufsize;
  }

  /** Constructor. */
  public SimpleCharStream(java.io.Reader dstream, int startline,
  int startcolumn, int buffersize)
  {
    inputStream = dstream;
    line = startline;
    column = startcolumn - 1;

    available = bufsize = buffersize;
    buffer = new char[buffersize];
  }

  /** Constructor. */
  public SimpleCharStream(java.io.Reader dstream, int startline,
                          int startcolumn)
  {
    this(dstream, startline, startcolumn, 4096);
  }

  /** Constructor. */
  public SimpleCharStream(java.io.Reader dstream)
  {
    this(dstream, 1, 1, 4096);
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader dstream, int startline,
  int startcolumn, int buffersize)
  {
    inputStream = dstream;
    line = startline;
    column = startcolumn - 1;

    if (buffer == null || buffersize != buffer.length)
    {
      available = bufsize = buffersize;
      buffer = new char[buffersize];
    }
    prevCharIsLF = prevCharIsCR = false;
    tokenStarted = false;
    endBuffer = null;
    tokenBegin = inBuf = maxNextCharInd = 0;
    bufpos = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader dstream, int startline,
                     int startcolumn)
  {
    ReInit(dstream, startline, startcolumn, 4096);
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader dstream)
  {
    ReInit(dstream, 1, 1, 4096);
  }
  /** Constructor. */
  public SimpleCharStream(java.io.InputStream dstream, String encoding, int startline,
  int startcolumn, int buffersize) throws java.io.UnsupportedEncodingException
  {
    this(encoding == null ? new java.io.InputStreamReader(dstream) : new java.io.InputStreamReader(dstream, encoding), startline, startcolumn, buffersize);
  }

  /** Constructor. */
  public SimpleCharStream(java.io.InputStream dstream, int startline,
  int startcolumn, int buffersize)
  {
    this(new java.io.InputStreamReader(dstream), startline, startcolumn, buffersize);
  }

  /** Constructor. */
  public SimpleCharStream(java.io.InputStream dstream, String encoding, int startline,
                          int startcolumn) throws java.io.UnsupportedEncodingException
  {
    this(dstream, encoding, startline, startcolumn, 4096);
  }

  /** Constructor. */
  public SimpleCharStream(java.io.InputStream dstream, int startline,
                          int startcolumn)
  {
    this(dstream, startline, startcolumn, 4096);
  }

  /** Constructor. */
  public SimpleCharStream(java.io.InputStream dstream, String encoding) throws java.io.UnsupportedEncodingException
  {
    this(dstream, encoding, 1, 1, 4096);
  }

  /** Constructor. */
  public SimpleCharStream(java.io.InputStream dstream)
  {
    this(dstream, 1, 1, 4096);
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream dstream, String encoding, int startline,
                          int startcolumn, int buffersize) throws java.io.UnsupportedEncodingException
  {
    ReInit(encoding == null ? new java.io.InputStreamReader(dstream) : new java.io.InputStreamReader(dstream, encoding), startline, startcolumn, buffersize);
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream dstream, int startline,
                          int startcolumn, int buffersize)
  {
    ReInit(new java.io.InputStreamReader(dstream), startline, startcolumn, buffersize);
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream dstream, String encoding) throws java.io.UnsupportedEncodingException
  {
    ReInit(dstream, encoding, 1, 1, 4096);
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream dstream)
  {
    ReInit(dstream, 1, 1, 4096);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream dstream, String encoding, int startline,
                     int startcolumn) throws java.io.UnsupportedEncodingException
  {
    ReInit(dstream, encoding, startline, startcolumn, 4096);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream dstream, int startline,
                     int startcolumn)
  {
    ReInit(dstream, startline, startcolumn, 4096);
  }
  /** Get token literal value. */
  public String GetImage()
  {
    if (bufpos >= tokenBegin)
      return new String(buffer, tokenBegin, bufpos - tokenBegin + 1);
    else
      return new String(buffer, tokenBegin, bufsize - tokenBegin) +
                            new String(buffer, 0, bufpos + 1);
  }

  /** Get the suffix. */
  public char[] GetSuffix(int len)
  {
    char[] ret = new char[len];

    if ((bufpos + 1) >= len)
      System.arraycopy(buffer, bufpos - len + 1, ret, 0, len);
    else
    {
      System.arraycopy(buffer, bufsize - (len - bufpos - 1), ret, 0,
                                                        len - bufpos - 1);
      System.arraycopy(buffer, 0, ret, len - bufpos - 1, bufpos + 1);
    }

    return ret;
  }

  /** Reset buffer when finished. */
  public void Done()
  {
    buffer = null;
  }

  /**
   * Method to adjust line and column numbers for the start of a token.
   * Later chars of the token continue from the new line and column.
   */
  public void adjustBeginLineColumn(int newLine, int newCol)
  {
    line = newLine;
    column = newCol;
    endBuffer = null;
  }
  public boolean getTrackLineColumn() { return trackLineColumn; }
  public void setTrackLineColumn(boolean tlc) { trackLineColumn = tlc; }
}
