## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

name: Apache Jena CI
# Manual
on: workflow_dispatch

#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java_version: ['17', '21']

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
    - name: Build with Maven
      run: mvn -e -B --file pom.xml  -pl :jena-fuseki-main -am install -Dmaven.javadoc.skip=true -Dmaven.source.skip=true install
